
GET http://localhost:5000/api/client
########

GET http://localhost:5000/api/client/1
########

POST http://localhost:5000/api/client
Content-Type: application/json

{
    "name": "Mcknight-Smith",
    "address": "92169 Thomas Mission",
    "city": "Barronchester",
    "zipCode": "33165",
    "province": "Michigan",
    "country": "United States",
    "contactName": "Teresa Davidson",
    "contactPhone": "+1-693-347-4889",
    "contactEmail": "nsullivan@example.com",
    "createdAt": "1970-09-26T19:12:30Z",
    "updatedAt": "1983-02-04T22:53:37Z"
}
########

PUT http://localhost:5000/api/client/1
Content-Type: application/json

{
    "id": 1,
    "name": "Mcknight-Smith Updated",
    "address": "Updated Address",
    "city": "Updated City",
    "zipCode": "12345",
    "province": "New Province",
    "country": "Updated Country",
    "contactName": "Updated Contact Name",
    "contactPhone": "+1-000-000-0000",
    "contactEmail": "updated_email@example.com",
    "createdAt": "1970-09-26T19:12:30Z",
    "updatedAt": "2024-12-09T15:30:00Z"
}
########

DELETE http://localhost:5000/api/client/1
########
