### Get all itemLines
GET http://localhost:5000/api/item_lines

### Get a specific itemLines by ID
GET http://localhost:5000/api/item_lines/5
Content-Type: application/json

### Update an existing itemLines
PUT http://localhost:5000/api/item_lines/5 
Content-Type: application/json
// je moet in de body de id ook meegeven 
{
    "Id": 5,
    "name": "nieuw",
    "description": "A123"
}

### DELETE an existing itemLines
DELETE  http://localhost:5000/api/itemlines/1
API_key: a1b2c3d4

Content-Type: application/json

