# Many-to-Many: Orders and Shipments

## Link orders to a shipment
POST http://localhost:5000/api/shipment/1/link-orders
Content-Type: application/json
api_key: a1b2c3d4

{
    "OrderIds": [1, 2]
}

###

## Get orders for a shipment
GET http://localhost:5000/api/shipment/1/orders
Content-Type: application/json
api_key: a1b2c3d4

###

## Disconnect orders from a shipment
POST http://localhost:5000/api/shipment/1/disconnect-orders
Content-Type: application/json
api_key: a1b2c3d4

{
    "OrderIds": [1, 2]
}

###

## Link shipments to an order
POST http://localhost:5000/api/order/1/link-shipments
Content-Type: application/json
api_key: a1b2c3d4

{
    "ShipmentIds": [1, 2]
}

###

## Get shipments for an order
GET http://localhost:5000/api/order/1/shipments
Content-Type: application/json
api_key: a1b2c3d4

###

# Orders

## Disconnect shipments from an order
POST http://localhost:5000/api/order/1/disconnect-shipments
Content-Type: application/json
api_key: a1b2c3d4

{
    "ShipmentIds": [1, 2]
}

###