
GET http://localhost:5000
########

GET http://localhost:5000/api/transfer
########


GET http://localhost:5000/api/transfer/1
########


POST http://localhost:5000/api/transfer
API_key: a1b2c3d4
Content-Type: application/json

{
    "id": 1,
    "reference": "TR00001",
    "transfer_from": null,
    "transfer_to": 9229,
    "transfer_status": "Completed",
    "created_at": "2000-03-11T13:11:14Z",
    "updated_at": "2000-03-12T16:11:14Z",
    "items": 
        
            "item_id": "P007435",
            "amount": 23
        
    
}
########


PUT http://localhost:5000/api/transfer/1
API_key: a1b2c3d4
Content-Type: application/json

{
    "id": 1,
    "reference": "TR00001",
    "transfer_from": null,
    "transfer_to": 9229,
    "transfer_status": "Incomplete",
    "created_at": "2000-03-11T13:11:14Z",
    "updated_at": "2024-03-12T16:11:14Z",
    "items": [
        {
            "item_id": "P007435",
            "amount": 23
        }
    ]
        
            
        
    
}
########


DELETE  http://localhost:5000/api/transfer/1
########

DELETE  http://localhost:5000/api/transfer/1
API_key: a1b2c3d4
########



