GET http://localhost:5000/api/v1/Warehouses
####

GET http://localhost:5000/api/v1/Warehouses/2
####

POST http://localhost:5000/api/v1/Warehouses/new
Content-Type: application/json

{
    "id": 3,
    "code": "BOYUDE7O",
    "name": "Pasewalk longterm location",
    "address": "Konrad-Seip-Allee 66",
    "zip": "49888",
    "city": "Pasewalk",
    "province": "Nordrhein-Westfalen",
    "country": "DE",
    "contactName": "Ullrich Beier",
    "contactPhone": "+49(0)8660 573483",
    "contactEmail": "vbarkholz@example.com",
    "created_at": "1979-10-03T07:33:35Z",
    "updated_at": "1993-08-05T16:12:41Z"
}

####


GET http://localhost:5000/api/Supplier/99999999


#######
POST http://localhost:5000/api/Supplier
Content-Type: application/json

{
        "Id": 99999999,
        "Code": "SUP0001",
        "Name": "testsupplier",
        "Address": "unknown",
        "AddressExtra": "Apt. 420",
        "City": "Port Anitaburgh",
        "ZipCode": "91688",
        "Province": "Illinois",
        "Country": "Czech Republic",
        "ContactName": "Toni Barnett",
        "PhoneNumber": "363.541.7282x36825",
        "Reference": "LPaJ-SUP0001"
}
