GET http://localhost:5000/api/item
###

GET http://localhost:5000/api/item/P000001
###


GET http://localhost:5000/api/item/
###


GET http://localhost:5000/api/item/P000001
###


GET http://localhost:5000/api/item/P000001
###


GET http://localhost:5000/api/item_groups
####