
GET http://localhost:5000/api/item/P000001
###


GET http://localhost:5000/api/item/P000001
###

GET http://localhost:5000/api/item/item-line/3
###

//moet nog item dingen maken zoals dat je kan zoeken op itemline etc