
GET http://localhost:5000/api/client/amount/2
########

GET http://localhost:5000/api/client/5314
########

POST http://localhost:5000/api/client
API_key: a1b2c3d4
Content-Type: application/json

{
  "name": "TEST",
  "address": "1296 Daniel Road Apt. 349",
  "city": "Pierceview",
  "zip_code": "28301",
  "province": "Colorado",
  "country": "United States",
  "contact_name": "Bryan Clark",
  "contact_phone": "242.732.3483x2573",
  "contact_email": "robertcharles@example.net",
}
########


POST http://localhost:5000/api/client
API_key: a1b2c3d4
Content-Type: application/json

{
    "name": "Mcknight-Smith",
    "address": "92169 Thomas Mission",
    "city": "Barronchester",
    "zipCode": "33165",
    "province": "Michigan",
    "country": "United States",
    "contactName": "Teresa Davidson",
    "contactPhone": "+1-693-347-4889",
    "contactEmail": "nsullivan@example.com",
    "createdAt": "1970-09-26T19:12:30Z",
    "updatedAt": "1983-02-04T22:53:37Z"
}
########


PUT http://localhost:5000/api/client/1
API_key: a1b2c3d4
Content-Type: application/json

{
    "id": 1,
    "name": "Mcknight-Smith Updated",
    "address": "Updated Address",
    "city": "Updated City",
    "zip_code": "123",
    "province": "New Province",
    "country": "Updated Country",
    "contact_name": "Updated Contact Name",
    "contact_phone": "+1-000-000-0000",
    "contact_email": "updated_email@example.com"
}
########

DELETE http://localhost:5000/api/client/9820
API_key: a1b2c3d4
########

