### Get All Item Types
GET http://localhost:5000/api/itemtypes
Content-Type: application/json

###

### Get a Single Item Type by ID
GET http://localhost:5000/api/itemtypes/2
Content-Type: application/json

###

### Create a New Item Type
POST http://localhost:5000/api/itemtypes
Content-Type: application/json

{
    "name": "Electronics",
    "description": "All electronic-related items"
}

###

### Update an Existing Item Type
PUT http://localhost:5000/api/itemtypes/1
Content-Type: application/json

{
    "name": "Updated Electronics",
    "description": "Updated description for electronics"
}

###

### Delete an Item Type
DELETE http://localhost:5000/api/itemtypes/5
Content-Type: application/json
