### Get all locations
GET http://localhost:5000/api/Location

###

### Get a specific location by ID
GET http://localhost:5000/api/Location/5

###

### Create a new location
POST http://localhost:5000/api/Location
Content-Type: application/json

{             
    "WareHouse_Id": 3,
    "Code": "A123",
    "Name": "Location A"
}

###

### Update an existing location
PUT http://localhost:5000/api/Location/5 
Content-Type: application/json
// je moet in de body de id ook meegeven 
{
    "Id": 5,
    "WareHouse_Id": 3,
    "Code": "B456",
    "Name": "Updated Location"
}


### DELETE an existing Location
DELETE  http://localhost:5000/api/Location/5 

