name: Python Tests for C# API / CI

on:
  pull_request:
    branches:
      - main # This triggers the action only on pull requests to the main branch
      - development # This triggers the action only on pull requests to the development branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # The job will run on the latest Ubuntu

    services:
      api:
        image: mcr.microsoft.com/dotnet/aspnet:8.0
        ports:
          - 5000:5000  # Expose port 3000 for your API
        env:
          ASPNETCORE_ENVIRONMENT: Development

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from the repository

    # Set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'  # Adjust based on your .NET version

    # Install EF Core tools globally (if needed)
    - name: Install EF Core tools globally
      run: |
        dotnet tool install --global dotnet-ef

    # Install .NET dependencies and build the API
    - name: Install dependencies and build API
      run: |
        dotnet restore Cargohub/Cargohub.csproj  # Restore project dependencies
        dotnet build Cargohub/Cargohub.csproj --no-restore  # Build the API

    # Run the API
    - name: Start API
      run: |
        cd Cargohub  # Navigate to the project folder (if not in root)
        dotnet run &  # Start the API in the background
        sleep 15  # Wait for the API to start

    # Set up Python environment (version 3.12.6)
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # Install Python dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Cargohub.Tests/requirements.txt  # Install dependencies listed in requirements.txt

    # Run Python tests
    - name: Run Python tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q Cargohub.Tests/ItemTests/test_items.py  # Run the tests
        pytest --maxfail=1 --disable-warnings -q Cargohub.Tests/ItemLinesTests/test_item_lines.py
        pytest --maxfail=1 --disable-warnings -q Cargohub.Tests/SupplierTests/test_suppliers.py
        pytest --maxfail=1 --disable-warnings -q Cargohub.Tests/InventoriesTests/test_inventories.py
        pytest --maxfail=1 --disable-warnings -q Cargohub.Tests/OrdersTests/test_orders.py
        pytest --maxfail=1 --disable-warnings -q Cargohub.Tests/ShipmentsTests/test_shipments.py
        pytest --maxfail=1 --disable-warnings -q Cargohub.Tests/ItemGroupsTests/test_item_groups.py
        pytest --maxfail=1 --disable-warnings -q Cargohub.Tests/ClientsTests/test_clients.py
